### ISSUE TITLE
change date format with GraphQL

### ISSUE THREAD

**Issue by jeetiss** [rlindskog/covid19-graphql#1]
Hello!

I need different time format for date (like. 2020-01-01). Can you help me with that?
I don't have experience with GraphQL but I want dive in, so if you help me with schema, I will try do my best

**Comment by rlindskog** [comment]
Hi! Is this for the return type or the input?

Return type: GraphQL and JSON don't have a date type, so dates are returned as Strings. I recommend converting the date string to a date object on the client. In javascript, that would be as simple as `const d = new Date('2020-01-01')`

Input: For the results query, it requires an input object, so you can do conditionals (eq, lt, gt - equals, less than, greater than). example below

```graphql
# Write your query or mutation here

query {
  # results
  results(countries: ["US"], date: { eq: "2020-03-16" })  {
    growthRate
    confirmed
  }
}

```

Hope this helps, please let me know if you have any more questions!

**Comment by rlindskog** [comment]
@jeetiss Also, check out the docs tab on the right, it shows a bunch of methods you can use.

<img width="1679" alt="Screen Shot 2020-03-17 at 11 36 22 AM" src="https://user-images.githubusercontent.com/7436773/76889852-916a9400-6843-11ea-9d29-dfee5b578b65.png">

**Comment by jeetiss** [comment]
@rlindskog thanks for answer.

>  I recommend converting the date string to a date object on the client.

I don't need date as object. I need date in different format. Date is formatting like `yyyy-M-d`, I need `yyyy-MM-dd`. I can do it on the client, but it costs much more than if it be converted on server.
<img width="566" alt="Снимок экрана 2020-03-18 в 08 50 53" src="https://user-images.githubusercontent.com/6726016/76929612-b28bbd00-68f5-11ea-83d5-2e99c8802de3.png">


I found where I saw that solution:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/types/date.js

What do you think about this?
