### ISSUE TITLE
Add CORS

### ISSUE THREAD

**Issue by jeetiss** [rlindskog/covid19-graphql#5]
Hello again 👋🏻

I can't use fetch without 'Access-Control-Allow-Origin' header
<img width="730" alt="Снимок экрана 2020-03-18 в 21 40 46" src="https://user-images.githubusercontent.com/6726016/76995703-49419380-6961-11ea-8163-7dc41ccc9a44.png">

**Comment by rlindskog** [comment]
Thanks! Fixed with https://github.com/rlindskog/covid19-graphql/pull/6

**Comment by rickkln** [comment]
This issue seems to have cropped up again randomly. Not sure why as I can't see any recent changes in this repo or mine.

<img width="1440" alt="Screenshot 2020-12-29 at 13 18 58" src="https://user-images.githubusercontent.com/533058/103280182-6b7c3d80-49d8-11eb-95c2-b07439c44fac.png">
