### ISSUE TITLE
uncaught exception: Syntax Error: Unexpected Name "country"  GraphQL request:2:5 

### ISSUE THREAD

**Issue by bonniesimon** [rlindskog/covid19-graphql#9]
I'm getting an error while using this api.

I used apollo to do the querying.

```

import ApolloClient from 'apollo-boost';
import {gql} from 'apollo-boost';


const client = new ApolloClient({
    uri: 'https://covid19-graphql.now.sh/',
});



client
  .query({
    query: gql`
    country (name: "India") {
        name
      }
    `
  })
  .then(result => console.log(result));
```

This is the code I used.

The following is the error I get with react: 

```
uncaught exception: Syntax Error: Unexpected Name "country"

GraphQL request:2:5
1 |
2 |     country (name: "India") {
  |     ^
3 |         name
```

**Comment by rlindskog** [comment]
Hey, you're query looks a little off, try this

```graphql
query {
  country(name: "India") {
    name
  }
}
```

It works in the [Graphiql editor](https://covid19-graphql.now.sh/), let me know if that works / you have any more questions!

**Comment by rlindskog** [comment]
@bonniesimon  Closing this for now, please reopen if my solution doesn't work or you have any more issues!
